# Reinforcement learining with quantum computing cloud Quafu

Before starting the journey of executing reinforcement learining(RL) task on real quantum devices with Quafu, you have to make sure the environment is consistent. The following code is based on python 3.8 to meet the need of the specific version of tensorflow. Then, you can install the follwing packages:

If you have GPUs, you can initialize and choose a specific device.

In [ ]:
!pip install pyquafu 
!pip install tensorflow==2.7.0
!pip install tensorflow-quantum==0.7.2
!pip install gym

In [1]:
import tensorflow as tf
# device
gpus = tf.config.list_physical_devices('GPU')
if gpus:
  # Restrict TensorFlow to only use the first GPU
  try:
    tf.config.set_visible_devices(gpus[0], 'GPU')
    logical_gpus = tf.config.list_logical_devices('GPU')
    print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPU")
  except RuntimeError as e:
    # Visible devices must be set before GPUs have been initialized
    print(e)

3 Physical GPUs, 1 Logical GPU


2023-03-05 18:21:17.938869: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-03-05 18:21:18.555896: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 22306 MB memory:  -> device: 0, name: GeForce RTX 3090, pci bus id: 0000:5b:00.0, compute capability: 8.6


The notebook gives an example of executing a well-trained parametrized quantum circuits as a RL agent, you can set the project path to store the model weights.

In [2]:
import sys
# update your projecty root path before running
sys.path.insert(0, ' ')
# for example, '/home/user/Documents/quantum_rl/nsga_net'

In [3]:
# model imports
import argparse
import re
import cirq
import gym
import numpy as np
from functools import reduce
from PIL import Image
from quafu import QuantumCircuit as quafuQC
from quafu import Task, User

import models.quantum_genotypes as genotypes
from models.quantum_models import generate_circuit
from models.quantum_models import generate_model_policy as Network
from models.quantum_models import get_model_circuit_params

Set some parameters about the RL task:

In [4]:
parser = argparse.ArgumentParser('Reinforcement learining with quantum computing cloud Quafu')
parser.add_argument('--env_name', type=str, default='CartPole-v1', help='environment name')
parser.add_argument('--state_bounds', type=np.array, default=np.array([2.4, 2.5, 0.21, 2.5]), help='state bounds')
parser.add_argument('--n_qubits', type=int, default=4, help='the number of qubits')
parser.add_argument('--n_actions', type=int, default=2, help='the number of actions')
parser.add_argument('--arch', type=str, default='NSGANet_id10', help='which architecture to use')
parser.add_argument('--model_path', type=str, default='./weights/weights_id10_quafu.h5', help='path of pretrained model')
args = parser.parse_args(args=[])

According to the results retrieved by Quafu, you can compute expectations with observables($Z_{0} * Z_{1} * Z_{2} * Z_{3}$ for CartPole) as the follwing function:

In [5]:
def get_res_exp(res):
    # access to probabilities of all possibilities 
    prob = res.probabilities
    sumexp = 0
    for k, v in prob.items():
        count = 0
        for i in range(len(k)):
            if k[i] == '1':
                count += 1
        if count % 2 == 0:
            sumexp += v
        else:
            sumexp -= v
    return sumexp

It's important to construct a process to send circuits to Quafu and get results from it. The next part shows the whole pipeline of involing Cirq circuits with Quafu and acquire expectations with quantum devices.

In [6]:
def get_quafu_exp(circuit):
    # convert Cirq circuts to qasm
    openqasm = circuit.to_qasm(header='')
    openqasm = re.sub('//.*\n', '', openqasm)
    openqasm = "".join([s for s in openqasm.splitlines(True) if s.strip()])
    
    # fill in with your token, register on website http://quafu.baqis.ac.cn/
    user = User()
    user.save_apitoken(" ")
    
    # initialize to Quafu circuits
    q = quafuQC(args.n_qubits)
    q.from_openqasm(openqasm)
    
    # create the task
    task = Task()
    task.load_account()
    
    # choose sampling number and specific quantum devices
    shots = 1000    
    task.config(backend='ScQ-P20', shots=shots, compile=True)
    task_id = task.send(q, wait=True).taskid
    print('task_id:', task_id)
    
    # retrieve the result of completed tasks and compute expectations
    task_status = task.retrieve(task_id).task_status
    if task_status == 'Completed':
        task = Task()
        task.load_account()
        res = task.retrieve(task_id)
        OB = get_res_exp(res)
    return task_id, tf.convert_to_tensor([[OB]])

The next post-processing layer apply stored action-specific weights on expectation values.

In [7]:
class Alternating_(tf.keras.layers.Layer):
    def __init__(self, obsw):
        super(Alternating_, self).__init__()
        self.w = tf.Variable(
            initial_value=tf.constant(obsw), dtype="float32", trainable=True, name="obsw")

    def call(self, inputs):
        return tf.matmul(inputs, self.w)

Then the softmax layer outputs the policy of the agent to choose next actions.

In [8]:
def get_obs_policy(obsw):
    process = tf.keras.Sequential([ Alternating_(obsw),
                                    tf.keras.layers.Lambda(lambda x: x * 1.0),
                                    tf.keras.layers.Softmax()
                                ], name="obs_policy")
    return process

Prepare for loading model weights:

In [9]:
qubits = cirq.GridQubit.rect(1, args.n_qubits)
genotype = eval("genotypes.%s" % args.arch)
ops = [cirq.Z(q) for q in qubits]
observables = [reduce((lambda x, y: x * y), ops)] # Z_0*Z_1*Z_2*Z_3
model = Network(qubits, genotype, args.n_actions, observables)
model.load_weights(args.model_path)

The follwing part builds an interaction between the agent in CartPole environment and Quafu. Every action choice means a task completed by quantum devices and finally, you can get a gif picturing the whole process.

In [10]:
# update gym to the version having render_mode, which is 0.26.1 in this file
# initialize the environment
env = gym.make(args.env_name, render_mode="rgb_array")
state, _ = env.reset()
frames = []

# set the number of episodes
for epi in range(20):
    im = Image.fromarray(env.render())
    frames.append(im)  
    
    # get PQC model parameters and expectations
    stateb = state/args.state_bounds
    newtheta, newlamda = get_model_circuit_params(qubits, genotype, model)
    circuit, _, _ = generate_circuit(qubits, genotype, newtheta, newlamda, stateb)
    _, expectation = get_quafu_exp(circuit)
    
    # get policy model parameters
    obsw = model.get_layer('observables-policy').get_weights()[0]
    obspolicy = get_obs_policy(obsw)
    policy = obspolicy(expectation)
    print('policy:', policy)
    
    # choose actions and make a step
    action = np.random.choice(args.n_actions, p=policy.numpy()[0])
    state, reward, terminated, truncated, _ = env.step(action)
    if terminated or truncated:
        print(epi+1)
        break
env.close()

# save to your path
frames[1].save(' ', save_all=True, append_images=frames[2:], optimize=False, duration=20, loop=0)
# for example, ./visualization/id10_quafu_gif/gym_CartPole_20.gif

task_id: 235443603A83BC7E


2023-03-05 18:22:09.155717: I tensorflow/stream_executor/cuda/cuda_blas.cc:1774] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.


policy: tf.Tensor([[0.17627509 0.8237249 ]], shape=(1, 2), dtype=float32)
task_id: 235445102B2B5C6F
policy: tf.Tensor([[0.35092312 0.6490769 ]], shape=(1, 2), dtype=float32)
task_id: 235445A0182D4907
policy: tf.Tensor([[0.40878502 0.591215  ]], shape=(1, 2), dtype=float32)
task_id: 235446100993C455
policy: tf.Tensor([[0.18885255 0.81114745]], shape=(1, 2), dtype=float32)
task_id: 235446702E7A25C8
policy: tf.Tensor([[0.34659508 0.6534049 ]], shape=(1, 2), dtype=float32)
task_id: 23544760206146B1
policy: tf.Tensor([[0.24671488 0.7532851 ]], shape=(1, 2), dtype=float32)
task_id: 2354496013E0AF23
policy: tf.Tensor([[0.20699283 0.7930072 ]], shape=(1, 2), dtype=float32)
task_id: 23544B6009A102F5
policy: tf.Tensor([[0.5094636  0.49053636]], shape=(1, 2), dtype=float32)
task_id: 23544D303B6D5932
policy: tf.Tensor([[0.62498325 0.3750167 ]], shape=(1, 2), dtype=float32)
task_id: 23544DB02377A6A1
policy: tf.Tensor([[0.33814445 0.6618555 ]], shape=(1, 2), dtype=float32)
task_id: 23544E20131C2E72
